name: Docker
on: 
  workflow_dispatch:
  
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Credentials
        env: 
          EMAIL: ${{ secrets.EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $EMAIL
              password $API_KEY
          EOF
      - name: CD
        env:
          APP: "clearfraction"
          EMAIL: ${{ secrets.EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
          DOCKER_OPTIONS: "--no-cache"
        run: |
          echo ${API_KEY} | docker login \
            --username=${EMAIL} \
            registry.heroku.com \
            --password-stdin
          docker build \
            ${DOCKER_OPTIONS} \
            --tag registry.heroku.com/clearfraction/web .
          heroku container:push web --app ${APP}
          heroku container:release web --app ${APP}
